# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.IntegerField()),
                ('stop_time', models.IntegerField()),
                ('client_ip', models.CharField(max_length=200)),
                ('exit_code', models.CharField(max_length=50)),
                ('attachment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cmd', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='server.Editor')),
            ],
        ),
    ]
