# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170420_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='cmd',
            field=models.CharField(max_length=10000),
        ),
    ]
